services:
  pnu-indi-schedule-front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pnu-indi-schedule-front
    restart: unless-stopped
    tty: true
    stdin_open: true
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=5
      - WATCHPACK_POLLING=true
      - HOST=0.0.0.0
    env_file:
      - ./.env
    ports:
      - "3002:3002"
      - "6004:6004"
    networks:
      - pnu-indi-schedule-net

networks:
  pnu-indi-schedule-net:
    driver: bridge
